let polishProverbs = [
"Adam cóż by poradził gdyby Bóg w raju Ewy nie posadził",
"Adwokat niech głowę a koń niech ma nogi",
"Afekty chociaż będą święte rozumem mają być ujęte",
"Aksamity atłasy sławy nie czynią",
"Ambroży w grudniu uprawia ugory",
"Ani Antoni na morzu wiatru nie dogoni",
"Ani w Boga wierzy ani się diabła boi",
"Aniołowie pijanych na rękach swych noszą",
"Apetyt rośnie w miarę jedzenia",
"Apostoł ludzkości rzadko pości",
"Baba z wozu koniom lżej",
"Bez pracy nie ma kołaczy",
"Będą takie mrozy że przymarznie cap do kozy",
"Biednemu zawsze wiatr w oczy",
"Bo pić to trzeba umieć",
"Bogatemu diabeł dzieci kołysze",
"Bogatemu to i byk się ocieli",
"Budować zamki na lodzie",
"Być kulą u nogi",
"Być pracowitym jak pszczoła",
"Byle do wiosny",
"Był w kościele ale na swoich chrzcinach",
"Chartom często przebaczają to za co kundla knutują",
"Chcesz być bogatym bądź siedem lat świnią",
"Chcesz przyjaciela stracić? Pieniędzy mu pożycz",
"Chcesz się dowiedzieć prawdy o sobie pokłóć się z przyjacielem",
"Chciwy dwa razy traci",
"Ciężko dźwigać żal porzucić",
"Co bardziej dokuczy to rychlej nauczy",
"Co cię nie zabije to cię wzmocni",
"Co dwie głowy to nie jedna",
"Co kraj to obyczaj",
"Co ma piernik do wiatraka?",
"Co się odwlecze to nie uciecze",
"Co się źle zaczyna to się dobrze kończy",
"Co wolno wojewodzie to nie tobie smrodzie",
"Co z oczu to z serca",
"Co za dużo to niezdrowo",
"Co zaszkodziło to nauczyło",
"Cudze chwalicie swego nie znacie Sami nie wiecie co posiadacie",
"Czapka na uchu a wesz na brzuchu",
"Człek zdechnie a robota zostanie",
"Czerwiec po deszczowym maju często dżdżysty w naszym kraju",
"Czego Jaś się nie nauczy tego Jan nie będzie umiał",
"Czerwiec stały grudzień doskonały",
"Czuć się jak ryba w wodzie",
"Czym chata bogata tym gościom rada",
"Czym skorupka za młodu nasiąknie tym na starość trąci",
"Czyste wino w głowę nie idzie",
"Czas to pieniądz",
"Daj kurze grzędę ona jeszcze wyżej siędę",
"Darowanemu koniowi w zęby się nie zagląda",
"Dasz pokój masz pokój",
"Deszcze listopadowe budzą wiatry grudniowe",
"Dla chcącego nic trudnego",
"Dlatego dwie uszy jeden język dano iżby mniej mówiono a więcej słuchano",
"Dobre dziatki to skarb matki",
"Dobrego i karczma nie zepsuje a złego i kościół nie naprawi",
"Dobrego więzienie nie zepsuje złego Kościół nie naprawi",
"Dobry adwokat zły sąsiad",
"Dobry zwyczaj nie pożyczaj jak oddaje jeszcze łaje",
"Dobry zwyczaj nie pożyczaj jeszcze lepszy nie oddawaj",
"Dobrymi chęciami piekło jest wybrukowane",
"Do grosza grosz to się napełni trzos",
"Doli swej koniem nie objedziesz",
"Do ludzi po naukę do matki po koszulę",
"Dopóty dzban wodę nosi dopóki mu się ucho nie urwie",
"Do Rzymu przez Krym",
"Do wesela się zagoi",
"Drzeć z kimś koty",
"Drzewa umierają stojąc",
"Dwóch było głupich na świecie: jeden co dawał drugi co nie chciał brać",
"Dziad jak odżyje to cię torbą zabije",
"Dzieci i ryby głosu nie mają",
"Dzień świętego Alojzego przyczynia wina dobrego",
"Dzisiaj żyjem jutro gnijem",
"Dziś wesoło jutro goło",
"Gdy Andrzej (30 XI) się zjawi to i ziemię postawi",
"Gdy dziecko upada Bóg ręce podkłada",
"Gdy jeleń wejdzie w moją puszczę to jeleń mój",
"Gdy kota nie ma myszy harcują",
"Gdy luty zimny i suchy sierpień będzie gorący",
"Gdy na Wawrzyńca (10 VIII) słota trzyma do Gromnic (2 II) lekka zima",
"Gdy pada w dniu świętej Anny pada aż do Zuzanny",
"Gdy przyjdzie święta Agnieszka przebija lód ogonem pliszka",
"Gdy przyjdzie święty Antoni znać jabłuszko na jabłoni",
"Gdy sierpień wrzos rozwija jesień krótka szybko mija",
"Gdy się człowiek spieszy to się diabeł cieszy",
"Gdy w adwencie szadź na drzewach się pokazuje to rok urodzajny nam zwiastuje",
"Gdy Zielona Matka (15 VIII) deszcz przynosi to zwykle na Narodzenie Matki (8 IX) rosi",
"Gdzie cienko tam się rwie",
"Gdzie diabeł nie może tam babę pośle",
"Gdzie drwa rąbią tam wióry lecą",
"Gdzie dwóch się bije tam trzeci korzysta",
"Gdzie Pan Bóg tam zwycięstwo",
"Gdzie Słowianin tam i pieśni",
"Gdyby ciocia miała wąsy byłaby wujaszkiem",
"Gdyby babcia miała wąsy to by była dziadkiem",
"Gdyby babcia miała drucik to by było radio",
"Gdyby kózka nie skakała toby nóżki nie złamała",
"Gdzie głupia rada tam zwada",
"Gdzie jest miód tam będą i pszczoły gdzie piękna dziewczyna tam będą i chłopcy",
"Gdzie kucharek sześć tam nie ma co jeść",
"Gdzie praca pilność na straży tam się bieda wejść nie waży",
"Gdzie zgoda tam i siła",
"Głaszcz chama to cię kopnie Kopnij chama to cię pogłaszcze",
"Głodnemu chleb na myśli",
"Głodny sytego nie zrozumie",
"Głodny kija się nie boi",
"Głos ludu głosem Boga",
"Głowa jak u śledzia nogi jak u niedźwiedzia",
"Głowa pusta jak kapusta",
"Głowa wielka a rozumu mało",
"Głową muru nie przebije(sz)",
"Głód najlepszy kucharz",
"Głupi kiedy milczy za mądrego ujdzie",
"Głupi ma zawsze szczęście",
"Głupich nie sieją sami się rodzą",
"Gość i ryba trzeciego dnia cuchnie",
"Gość nie w porę gorszy Tatarzyna",
"Gość w dom Bóg w dom",
"Gość w domu baba w ciąży",
"Góra urodziła mysz",
"Grosz do grosza a będzie kokosza",
"Groźniejsze jest wojsko jeleni przy lwie hetmanie niż wojsko lwów przy hetmanie jeleniu",
"Grzej się Ewka kiedy się palą drewka",
"Grzmot listopada dużo zboża zapowiada",
"Hulaj dusza piekła nie ma",
"Hulaj duszo pókiś młoda",
"I ja waść i ty waść a kto będzie świnie paść?",
"I kwaśne jabłko robak toczy",
"Im więcej w grudniu pogody tym więcej wiosną wody",
"Indyk myślał o niedzieli a w sobotę łeb mu ścieli",
"Jajko mądrzejsze od kury",
"Jaka głowa taka mowa",
"Jaka praca taka płaca",
"Jaka ziemia taka góra jaka matka taka córa",
"Jak cię widzą tak cię piszą",
"Jakie drzewo taki klin jaki ojciec taki syn",
"Jakie jabłko taka skórka jaka matka taka córka",
"Jakie pytanie taka odpowiedź",
"Jakie życie taka śmierć",
"Jaki pan taki kram",
"Jak kamień w wodę",
"Jak krew w piach",
"Jak Kuba Bogu tak Bóg Kubie",
"Jak na świętego Antoniego chmurki to z ziemniakami na górki",
"Jak pies je to nie szczeka bo mu miska ucieka",
"Jak się człowiek śpieszy to się diabeł cieszy",
"Jak się jednego dnia uchla to na drugi robaka zakropi",
"Jak się matka z córką zgłosi tak się koniec grudnia nosi",
"Jak się nie ma co się lubi to się lubi co się ma",
"Jak się powiedziało a pora powiedzieć b",
"Jak sobie pościelesz tak się wyśpisz",
"Jak suka nie da to pies nie weźmie",
"Jak śmierć koło pupy to do pokuty",
"Jak trwoga to do Boga",
"Jak ty komu tak on tobie",
"Jak za króla Sasa Jedz pij i popuszczaj pasa",
"Jak zgłodnieje sam przyjdzie",
"Jedna gęś dwie niewieście będzie dzisiaj jarmark w mieście",
"Jedna jaskółka wiosny nie czyni",
"Jednym uchem wchodzi a drugim wychodzi",
"Jeszcze się taki nie urodził co by każdemu dogodził",
"Jeśli moje zdanie dobrze mówisz Janie",
"Jeśli nie potrafisz nie pchaj się na afisz",
"Kapelusik z piórami a wszy wyłażą dziurami",
"Kapelusz sombrero a w kieszeni zero",
"Karp ryba jeleń zwierzyna",
"Każda broń palna raz do roku strzela sama",
"Każdy kij ma dwa końce",
"Każdy ma to na co sobie zasłużył",
"Kląć jak szewc",
"Kłamstwo jak oliwa zawsze na wierzch wypływa",
"Kłamstwo ma krótkie nogi",
"Kombinuje jak koń pod górę",
"Komu Pan Bóg darzy suka jemu prosięta urodzi",
"Koniec języka za przewodnika",
"Koń ma cztery nogi a też się potknie",
"Kowal zawinił cygana powiesili",
"Kruk krukowi oka nie wykole",
"Kto nie pracuje ten nie je",
"Kto ma pszczoły ten ma miód kto ma dzieci ten ma smród",
"Kto ma pobrzękacze ma i posługacze",
"Kto mieczem wojuje ten od miecza ginie",
"Kto pierwszy ten lepszy",
"Kto pod kim dołki kopie ten sam w nie wpada",
"Kto pyta ten nie błądzi",
"Kto rano wstaje temu Pan Bóg daje",
"Kto sieje wiatr ten zbiera burze",
"Kto się buduje procesuje i leczy tego bieda ćwiczy",
"Kto się przerzuci z wódki na mleko nie pociągnie daleko",
"Kuj żelazo póki gorące",
"Kwiecień plecień co przeplata trochę zimy trochę lata",
"Kto ziarno sieje ten przed burzą zwieje",
"Krzykiem skrzypiec nie nastroisz",
"Leje jak z cebra",
"Lepiej nie dosolić niż przesolić",
"Lepiej się ukłonić głowie niż ogonowi",
"Lepiej z mądrym zgubić niż z głupim znaleźć",
"Lepiej że na głowie niż w głowie łyso",
"Lepsza jedna panna niż cztery wdowy",
"Lepsza u matki polewka niż u obcych marcepany",
"Lepsze jest wrogiem dobrego",
"Lepszy rydz niż nic",
"Lepszy wróbel w garści niż gołąb na dachu",
"Licho nie śpi",
"Ładnemu we wszystkim ładnie",
"Łatwiej kołek obcinkować niż go później pogrubasić",
"Łatwiej pałac skrytykować niż psu budę postawić",
"Łatwowierność rodzi oszustów",
"Ma coś z rycerza zakuty łeb",
"Maj z grzmotami rok dobry przed nami",
"Małe dzieci mały kłopot duże dzieci duży kłopot",
"Mądra matka dba o swe córki",
"Mądrej głowie dość dwie słowie",
"Mądrej głowy włos się nie trzyma",
"Mądrej mamie mało dwie córki",
"Mądry Polak po szkodzie",
"Miłe złego początki",
"Modli się pod figurą a diabła ma za skórą",
"Mokry deszczu się nie boi",
"Mowa jest srebrem a milczenie złotem",
"Mów do słupa a słup jak dupa",
"Mówił dziad do obrazu a ten do niego ani razu",
"Mieć dwie lewe ręce",
"Miłość od pierwszego wejrzenia",
"Mój dom jest moją twierdzą",
"Na adwokackim wozie często musisz oś smarować",
"Na Agnieszkę mróz składaj chłopie wóz",
"Na Alberta sianokosów pełna sterta",
"Na Andrzeja mróz gotuj na zimę wóz a jak taje to znów sanie",
"Na frasunek dobry trunek",
"Na głowie kapelusz a z głowy rozumu ani rus",
"Na głupiej głowie i włos się nie utrzyma",
"Na kogo kruki na tego wrony",
"Na koniu jedzie a konia nie widzi",
"Na pieniądzach świat nie stoi",
"Na pochyłe drzewo każda koza wlezie",
"Na to daje gębie papać by umiała dobrze kłapać",
"Na świętą Annę mrowiska szukaj w zimie ogniska",
"Na świętego Albina rzadka u ludzi mina bo post się zaczyna",
"Na święty Ambroży poprawią się mrozy",
"Na święty Antoni pierwsza się jagódka zapłoni",
"Na święty Walenty uciekają z domu centy",
"Na złodzieju czapka gore",
"Nadgorliwość gorsza od faszyzmu",
"Najlepsze mienie czyste sumienie",
"Natura ciągnie wilka do lasu",
"Nauka nie poszła w las",
"Nawet mistrzowi nie zaszkodzi nauka",
"Ni to pies ni wydra coś na kształt świdra",
"Ni to pies ni zając",
"Nie budź licha kiedy śpi",
"Nie chce góra przyjść do Mahometa musi Mahomet przyjść do góry",
"Nie chcesz słuchać matki ni ojca to posłuchaj psiej skóry",
"Nie chwal dnia przed zachodem słońca",
"Nie czyń bliźniemu co tobie nie miłe",
"Nie dasz chłopakom to dasz robakom",
"Nie dla psa kiełbasa nie dla kota spyrka",
"Nie dla psa kiełbasa nie dla prosiąt miód",
"Nie każda głowa siwa mądra bywa",
"Nie kupuj kota w worku",
"Nie mów hop póki nie przeskoczysz",
"Nie mów nikomu co się dzieje w domu",
"Nie mów o nikim nie będą o tobie",
"Nie ma dymu bez ognia",
"Nie ma róży bez kolców",
"Nie ma reguły bez wyjątku",
"Nie ma tego złego co by na dobre nie wyszło",
"Nie masz na upór lekarstwa",
"Nie miała baba kłopotu kupiła sobie prosię",
"Nie miejsce zdobi człowieka lecz człowiek miejsce",
"Nie od razu Kraków zbudowano",
"Nie pożyczywszy na tydzień gniewu pożyczywszy na cały rok",
"Nie pomoże atłas kiedy w brzuch nie natkasz",
"Nie pomoże mydło ani malowidło ani studnia wody jak nie ma urody",
"Nie pomoże puder róż kiedy gęba stara już",
"Nie pomoże uczoność ani nieskończoność ani fura sprzętu jak nie ma talentu",
"Nie rób drugiemu co tobie nie miłe",
"Nie samym chlebem człowiek żyje",
"Nie szata zdobi człowieka",
"Nie szata zdobi człowieka lecz człowiek szatę",
"Nie taki diabeł straszny jak go malują",
"Nie śmiej się dziadku z czyjegoś wypadku dziadek się śmiał i to samo miał",
"Nie święci garnki lepią",
"Nie ucz księdza pacierza",
"Nie ucz matki jak się dzieci robi",
"Nie ucz ojca dzieci robić",
"Nie wchodzi się dwa razy do tej samej rzeki",
"Nie widziała dupa słońca",
"Nie wie głowa co język bełkocze",
"Nie wsadzaj nosa do cudzego prosa",
"Nie wszystko się godzi co wolno",
"Nie wszystko złoto co się świeci",
"Nie wywołuj wilka z lasu",
"Nie z każdej mąki będzie chleb",
"Niedaleko pada jabłko od jabłoni",
"Niejeden rekin sobie życzy by dorodna szprotka wiodła go na smyczy",
"Niemiła księdzu ofiara chodź cielę do domu",
"Nieszczęścia chodzą parami",
"Nikt się mądrym nie rodzi ale staje",
"Nosił wilk razy kilka ponieśli i wilka",
"O pieniądzach się nie mówi pieniądze się ma",
"Od piwa głowa się kiwa",
"Od wódki rozum krótki",
"Od przybytku głowa nie boli",
"Ogień i woda dobrzy słudzy lecz źli gospodarze",
"Od świętej Anki zimne wieczory i poranki",
"Pasuje jak piąte koło u wozu",
"Pasuje jak kij do dupy",
"Pasuje jak świni siodło",
"Póki życia póty nauki",
"Póty dzban wodę nosi póki się ucho nie urwie",
"Pańskie oko konia tuczy",
"Pan Bóg dopuści to i z kija wypuści / wystrzeli/",
"Pan Bóg nie rychliwy ale sprawiedliwy",
"Pieniądze szczęścia nie dają",
"Pierwej rozważ potem odważ",
"Pierwsze śliwki robaczywki",
"Pies ogrodnika; samemu nie zje i drugiemu nie da",
"Pies który głośno szczeka nie ugryzie",
"Po burzy zawsze słońce przychodzi",
"Po świętej Agacie wyschną na słońcu gacie",
"Po świętej Agacie wyschnie bielizna na płocie",
"Począwszy od Adama to każdy człowiek kłamca",
"Pokorne ciele to ciele",
"Pokorne cielę dwie matki ssie",
"Polska dla Polaków Ziemia dla ziemniaków",
"Polski żołnierz w obozie anioł w polu lew",
"Porywać się z motyką na słońce",
"Postać anielska dusza diabelska",
"Potrzebne jak dziura w moście",
"Potrzebne jak zającowi dzwonek na polowaniu",
"Poznać łatwo w starości jaki kto był w młodości",
"Poznać pana po cholewach",
"Poznasz głupiego po śmiechu jego",
"Praca nie zając nie ucieknie",
"Prawda w oczy kole",
"Prawda zawsze zwycięża",
"Prawdziwa wiedza to znajomość przyczyn",
"Prawdziwego przyjaciela poznaje się w biedzie",
"Przyganiał kocioł garnkowi a sam smoli",
"Przyjaciela szukaj blisko wroga daleko",
"Przyszła koza do woza",
"Przyszła kryska na Matyska",
"Przyzwyczajenie jest drugą naturą",
"Psy szczekają a karawana idzie dalej",
"Pycha i z nieba spycha",
"Rób a rób zarobisz na grób",
"Ranne wstawanie i wczesna żeniaczka jeszcze nikomu nie zaszkodziły",
"Raz na wozie raz pod wozem",
"Ręka rękę myje",
"Słówko wyleci wróblem a powróci wołem",
"Słońcu i miłości nigdy się w oczy nie patrzy",
"Słowo się rzekło kobyłka u płota",
"Słowo szkody nie nagrodzi",
"Służ panu wiernie on ci za to pierdnie",
"Sam sobie sterem żeglarzem okrętem",
"Samotnemu cały świat pustynią",
"Sen mara Bóg wiara",
"Skleroza nie choroba tylko nogi bolą",
"Sprawiedliwość bez dobroci okrucieństwem jest",
"Stara miłość nie rdzewieje",
"Stare buty najwygodniejsze",
"Stare wino żona młoda niejednemu życia doda",
"Starego wróbla na plewy nie złapiesz",
"Starość nie radość śmierć nie wesele",
"Stary a głupi",
"Stary ale jary",
"Starych drzew się nie przesadza",
"Stoi jak wół na granicy",
"Strach ma wielkie oczy",
"Strzeżonego Pan Bóg strzeże",
"Suchy marzec mokry maj będzie żytko niby gaj",
"Swoje brudy trzeba prać w domu",
"Syty głodnego nie zrozumie",
"Szczęście ciska ludźmi jak piłką",
"Szczęście człowieka psuje nieszczęście hartuje",
"Szczęście czego mi nie dało tego mi nie będzie brało",
"Szczęście dziś matką a jutro może być macochą",
"Szczęście głupim sprzyja",
"Szczęście gdy trafi na głupiego wszystkim go czyni nieznośnego",
"Szczęśliwi czasu nie liczą",
"Szewc bez butów chodzi",
"Szlachcic na zagrodzie równy wojewodzie",
"Szukajcie a znajdziecie",
"Szukać igły w stogu siana",
"Szybka decyzja to połowa zwycięstwa Ś",
"Ściany mają uszy",
"Ślepy afekt i pamięć z człowieka wywlecze",
"Ślusarz zawinił a kowala powiesili",
"Śmieje się jak głupi do sera",
"Śpiesz się powoli",
"Święta Agnieszka wypuszcza skowronka z mieszka",
"Święty Alojzy miód w plastrach dojrzy",
"Święty Antoni o gryce siać przypomni",
"Święty Antoni od zguby broni",
"Święty Antoni złodziei goni",
"Tak krawiec kraje jak mu materii staje",
"Taki z niego muzykant jak z koziego ogona klarnet a z koziej dupy trąba",
"Tanie mięso psy jedzą",
"Tanie kupisz psom wyrzucisz",
"Ten się nie myli kto nic nie robi",
"Ten się śmieje kto się śmieje ostatni",
"Tonący brzytwy się chwyta",
"Trafiła kosa na kamień",
"Trafiło się ślepej kurze ziarno",
"Trudno dwóm panom służyć",
"Trunek mocny białogłowa grzeszna z najmędrszego uczynią błazna",
"Tylko krowa zdania nie zmienia",
"Tylko trzewik wie że pończocha dziurawa",
"Tym chata boga czym goście wymiotują",
"U skąpego zawsze po obiedzie",
"Ubóstwo cnoty nie traci",
"Ubóstwo nie hańbi",
"Ubóstwo nie jest ohydą",
"Ubóstwo nikogo nie krzywdzi",
"Ubóstwo szlachectwa nie traci",
"Ubóstwo śmierci się równa",
"Ubóstwo uczciwe nie bywa wstydliwe",
"Ubiegają się jak dwa psy o jedną kość",
"Ubogi żywi się jak może a bogaty jako chce",
"Ubogi mało ma przyjaciół",
"Ubogi nie ma tego owego a bogacz łakomy wszystkiego",
"Ubogi za psa u bogacza stoi",
"Ubogi jak mysz kościelna",
"Ubogiego zdanie: nie dba nikt na nie",
"Ubogiemu łacniej być dobrym",
"Ubogiemu dzieciątko bogatemu cielątko",
"Ubogiemu kawał chleba to most do nieba",
"Ubogiemu zawsze wiatr w oczy a droga pod górkę",
"Ubogiemu zawsze wiatr w oczy",
"Ubrał się jak dudek w pawie pióra",
"Ubrał się jak stróż w Boże Ciało",
"Ubrany jak pan a głupi jak baran",
"Ucieczka jest zawsze haniebna ale czasem zbawienna",
"Ucieczka winnym czyni",
"Ucieka świńskim truchtem",
"Ucieka aż się za nim kurzy",
"Ucieka jak Cygan na kradzionym koniu",
"Ucieka jak od zgniłego psa",
"Ucieka jak pies oparzony",
"Ucieka jak przed zbrojnymi goły",
"Ucieka jak zając przed chartem",
"Uciekającego i bojaźliwy goni",
"Uciekać nie ładnie ale pożytecznie",
"Ucz się ucz bo nauka to do potęgi klucz",
"Uczący drugich sam się uczy",
"Uczepił się jak pchła kożucha",
"Uczonego zawsze kochają nieuczonym wszędzie pogardzają",
"Uczonym nie łacno zostać",
"Uczył Marcin Marcina a sam głupi jak świnia",
"Uderz w stół a nożyce się odezwą",
"Umarłego płaczem nie wskrzesi",
"Umarłych zęby nie bolą",
"Umierający człowiek nie zginie",
"Umiesz liczyć licz na siebie",
"Upartego i kijem nie przekona",
"Upadł na rozumie",
"Upił się jak bąk",
"Upił się jak świnia",
"Uroda rzecz nietrwała",
"Urodził się ochrzcili podrósł ożenili umarł pochowali i na grobie napisali że był błazen",
"Uszom prędzej można dogodzić niż oczom",
"W adwenta same posty i święta",
"W czerwcu się okaże co nam rok da w darze",
"W dnie kieliszka wszystko znika",
"W krótkie dzionki października wszystko z pola z sadu znika",
"W lipcu dzień mglisty jesienią czas dżdżysty",
"W lipcu upały wrzesień doskonały",
"W lipcu upały w grudniu mróz ostry i stały",
"W listopad liść z drzewa opadł",
"W listopadzie ziemia ciepła zima będzie skrzepła",
"W lutym aura burzowa wiosna rychliwa",
"W lutym śnieg i mróz stały czynią w lecie upały",
"W marcu jak w garncu",
"W marcu śnieżek sieje a czasem słonko grzeje",
"W Narodzenie Panny Marii (8 XI) pogodnie będzie tak cztery tygodnie",
"W piątek zły początek",
"W starym piecu diabeł pali",
"W święty August koniec burz",
"W tym największy jest ambaras żeby dwoje chciało naraz",
"W zdrowym ciele zdrowy duch",
"Wesoło w maju ze słowikiem w gaju",
"Widać po słowie co u kogo w głowie",
"Wiedzą sąsiedzi jak kto siedzi",
"Większa moc boska niż złość ludzka",
"Wszędzie dobrze ale w domu najlepiej",
"Wszędzie dobrze gdzie nas nie ma",
"Wszystko dobre co się dobrze kończy",
"Wszystko ma swój koniec",
"Wszystko co dobre szybko się kończy",
"Wybiera się jak sójka za morze",
"Wysoki do nieba a głupi jak trzeba",
"Wysoki jak brzoza a głupi jak koza",
"Wysoki jak topola a głupi jak fasola",
"Wystroił się jak stróż w Boże ciało",
"Wyszło szydło z worka",
"Wyśpisz się po śmierci",
"Z deszczu pod rynnę",
"Z dużej chmury mały deszcz",
"Z dzieła poznaje się człowieka",
"Z jedynaka jak nie pies to sabaka",
"Z pustego i Salomon nie naleje",
"Z tej mąki chleba nie będzie",
"Złego diabli nie biorą",
"Złej baletnicy szkodzi rąbek przy spódnicy",
"Za Augusta ziemia pusta",
"Za cierpienie da Bóg zbawienie",
"Za dukata brat sprzeda brata",
"Za mundurem panny sznurem",
"Za króla Olbrachta wyginęła szlachta",
"Zapomniał wół jak cielęciem był",
"Zbój zbója pogoni",
"Zgoda buduje niezgoda rujnuje",
"Ziarnko do ziarnka aż zbierze się miarka",
"Zrób dziś co masz zrobić jutro",
"Zrób komu dobrze to ci da po ziobrze",
"Żebro Adamowe nie przynosi tak wiele pożytku jak szkody"
]